"""Phase 4 production-hardening contracts with no deployment authority."""

from .database_abstraction import (
    DatabaseAccessMode,
    DatabaseAdapter,
    DatabaseAdapterRegistry,
    DatabaseAdapterUnavailableError,
    DatabaseAvailability,
    DatabaseBackend,
    DatabaseCapabilities,
    DatabaseConfigurationError,
    DatabaseConnection,
    DatabaseError,
    DatabaseHealth,
    DatabaseReadOnlyError,
    DatabaseTarget,
    DatabaseTenantIsolationError,
    REQUIRED_CAPABILITIES,
    SQLiteDatabaseAdapter,
    SQLiteDatabaseConnection,
    TenantStateRepository,
    decode_exact_decimal,
    encode_exact_decimal,
)

__all__ = [
    "DatabaseAccessMode",
    "DatabaseAdapter",
    "DatabaseAdapterRegistry",
    "DatabaseAdapterUnavailableError",
    "DatabaseAvailability",
    "DatabaseBackend",
    "DatabaseCapabilities",
    "DatabaseConfigurationError",
    "DatabaseConnection",
    "DatabaseError",
    "DatabaseHealth",
    "DatabaseReadOnlyError",
    "DatabaseTarget",
    "DatabaseTenantIsolationError",
    "REQUIRED_CAPABILITIES",
    "SQLiteDatabaseAdapter",
    "SQLiteDatabaseConnection",
    "TenantStateRepository",
    "decode_exact_decimal",
    "encode_exact_decimal",
]
