"""Synthetic harness acceptance; no native evidence is generated by these tests."""
from datetime import timedelta
import json

import pytest

from backend.market_data.native_certification_v1 import NativeCertificationCaptureV1, certify_startup
from backend.tests.test_ninjatrader_market_sprint11 import setup, hello, frame, bar, api_settings, SESSION
from backend.tests.test_session_lifecycle_sprint12 import stamp


def send(capture, f):
    with capture.reader.path.open("ab") as file:
        file.write((json.dumps(f)+"\n").encode())
    return capture.poll()


@pytest.mark.parametrize("purpose", ["market_open", "daily_boundary"])
def test_bounded_market_and_boundary_capture(api_settings,tmp_path,purpose):
    start=stamp("2026-09-14T15:58:00-05:00")
    r,clock=setup(tmp_path,start=start)
    capture=NativeCertificationCaptureV1(r,purpose=purpose)
    send(capture,hello(r,clock))
    send(capture,bar(clock,1,"FORMING",bar_time=(clock[0]+timedelta(minutes=1)).isoformat()))
    send(capture,bar(clock,2))
    target=stamp("2026-09-14T18:01:00-05:00")
    while clock[0] < target:
        clock[0]+=timedelta(seconds=5)
        send(capture,frame(clock,r.sequence+1))
        # Explicit synthetic source sends only complete eligible intervals.
        prior=clock[0]-timedelta(minutes=1)
        hours=r.service.gate.market_hours.get_market_hours_service()
        if clock[0].second == 0 and hours.is_market_open(symbol="NQ",timestamp=prior) and hours.is_market_open(symbol="NQ",timestamp=clock[0]-timedelta(microseconds=1)):
            send(capture,bar(clock,r.sequence+1))
    report=capture.report()
    assert report["evidence_kind"] == "SYNTHETIC_OFFLINE"
    assert report["status"] == "PENDING_NATIVE_CERTIFICATION"
    assert all(report["milestones"].values())
    assert report["observed_market_milestones_complete"]
    assert report["canonical_candles"] == 63
    assert report["htf"] == {"15m":4,"1h":1}
    assert report["broker_order_calls"] == report["account_drift"] == report["completed_trades"] == report["journal_completed"] == 0
    assert report["sim_execution_authority"] == "DISABLED"
    original_snapshot = r.get_snapshot
    r.get_snapshot = lambda: {**original_snapshot(), "latest_decision": None}
    assert capture.report()["observed_market_milestones_complete"]
    if purpose == "daily_boundary":
        r.get_snapshot = lambda: {**original_snapshot(), "htf_current_session": {"15m":0,"1h":0}}
        assert not capture.report()["observed_market_milestones_complete"]
    capture.close()


@pytest.mark.parametrize("kind",["duplicate","late","gap","disconnect","malformed"])
def test_failed_capture_never_certifies_or_executes(api_settings,tmp_path,kind):
    r,clock=setup(tmp_path)
    c=NativeCertificationCaptureV1(r,purpose="market_open")
    send(c,hello(r,clock))
    send(c,bar(clock,1))
    bad=frame(clock,2)
    if kind == "duplicate": bad=bar(clock,1)
    if kind == "late": bad["event_time"]=(clock[0]-timedelta(minutes=1)).isoformat()
    if kind == "gap": bad["sequence"]=5
    if kind == "disconnect": bad["kind"]="DISCONNECTED"
    if kind == "malformed": bad["payload"]=[]
    with pytest.raises(ValueError): send(c,bad)
    report=c.report()
    assert report["status"] == "FAIL_CLOSED"
    assert report["broker_order_calls"] == report["completed_trades"] == 0
    c.close()


def test_forming_ohlcv_is_audited_without_creating_a_canonical_candle(api_settings,tmp_path):
    r,clock=setup(tmp_path)
    c=NativeCertificationCaptureV1(r,purpose="market_open")
    send(c,hello(r,clock))
    with pytest.raises(ValueError): send(c,bar(clock,1,"FORMING",high=9999))
    assert c.report()["status"] == "FAIL_CLOSED"
    assert r.service.gate.closed_count == 0 and r.service._runtime is None
    c.close()


def sidecar(path):
    now=stamp("2026-09-14T09:00:00-05:00")
    p=dict(same_source=True,source_present=True,callback_present=True,source_snapshot_stable=True,
        source_price_status="Connected",source_connection_status="Connected",source_price_status_after="Connected",
        source_connection_status_after="Connected",callback_price_status="Connected",callback_connection_status="Connected",
        callback_previous_price_status="Connecting",callback_previous_connection_status="Connecting",
        callback_provider="SYNTHETIC_FIXTURE",source_provider="SYNTHETIC_FIXTURE",decision="CONTINUE")
    row=dict(schema="arms.nt.connection-diagnostic.v1",session=SESSION,sequence=0,kind="CONNECTION_STATUS",
        event_time=now.isoformat(),callback_received_time=now.isoformat(),payload=p)
    path.write_text(json.dumps(row)+"\n")
    return row,now+timedelta(seconds=5)


@pytest.mark.parametrize("mutation", ["none","provider","state","session","sequence","time","no_alignment","truncated","oversize"])
def test_sidecar_proof_is_mandatory(tmp_path,mutation):
    path=tmp_path/"sidecar.jsonl"
    row,hello_time=sidecar(path)
    if mutation == "provider": row["payload"]["source_provider"]="other"
    if mutation == "state": row["payload"]["source_price_status"]="Connecting"
    if mutation == "session": row["session"]="other"
    if mutation == "sequence": row["sequence"]=True
    if mutation == "time": row["event_time"]=(hello_time+timedelta(seconds=1)).isoformat()
    if mutation == "no_alignment": row["payload"]["decision"]="WAIT_STARTUP_ALIGNMENT"
    path.write_text(json.dumps(row)+("" if mutation == "truncated" else "\n"))
    if mutation == "oversize": path.write_bytes(b"x"*1_000_001+b"\n")
    if mutation == "none":
        assert certify_startup(path,SESSION,hello_time,"SYNTHETIC_FIXTURE")["status"] == "PASS"
    else:
        with pytest.raises(ValueError): certify_startup(path,SESSION,hello_time,"SYNTHETIC_FIXTURE")
